/*
 * include/osZ/bits/ui.h - GENERATED BY elftool DO NOT EDIT THIS FILE
 *
 * Copyright (c) 2017 bzt (bztsrc@gitlab)
 * https://creativecommons.org/licenses/by-nc-sa/4.0/
 *
 * You are free to:
 *
 * - Share — copy and redistribute the material in any medium or format
 * - Adapt — remix, transform, and build upon the material
 *     The licensor cannot revoke these freedoms as long as you follow
 *     the license terms.
 *
 * Under the following terms:
 *
 * - Attribution — You must give appropriate credit, provide a link to
 *     the license, and indicate if changes were made. You may do so in
 *     any reasonable manner, but not in any way that suggests the
 *     licensor endorses you or your use.
 * - NonCommercial — You may not use the material for commercial purposes.
 * - ShareAlike — If you remix, transform, or build upon the material,
 *     you must distribute your contributions under the same license as
 *     the original.
 *
 * @brief OS/Z system calls for ui service. Include with osZ.h
 */

#define SYS_flush	(0x0c)
#define SYS_devprogress	(0x0f)
#define SYS_keyrelease	(0x18)
#define SYS_setpixbuf2	(0x19)
#define SYS_setcursor	(0x1b)
#define SYS_eventmask	(0x22)
#define SYS_pointer	(0x26)
#define SYS_resizewindow	(0x2c)
#define SYS_opendisplay	(0x2d)
#define SYS_unmapwindow	(0x31)
#define SYS_mapwindow	(0x36)
#define SYS_setwindowtitle	(0x38)
#define SYS_createwindow	(0x47)
#define SYS_destroywindow	(0x48)
#define SYS_focuswindow	(0x4f)
#define SYS_movewindow	(0x50)
#define SYS_datapacket	(0x52)
#define SYS_keypress	(0x53)

